version: "2"
services:
  question-overflow:
    image: "node:8"
    container_name: "question-overflow-app"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - /opt/question-overflow/source-code:/home/node/app
    ports:
      - "11000:3000"
    env_file:
      - ./env/production.env
    links:
      - mongodb
    depends_on:
      - mongodb
    command: "npm run start-prod"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /opt/question-overflow/data:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
